name: Check Pull Request Title and Mandatory Checkboxes ☑

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pr_title_and_checkboxes:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title and Mandatory Checkboxes (if Feature/Fix)
        uses: actions/github-script@v6
        with:
          script: |
            const prTitle = context.payload.pull_request.title.toLowerCase();
            const prBody = (context.payload.pull_request.body || "").toLowerCase();

            const isFeature = prTitle.startsWith("add feature: ");
            const isFix = prTitle.startsWith("fix: ");
            const isChore = prTitle.startsWith("chore: ");

            if (!(isFeature || isFix || isChore)) {
              throw new Error('Invalid PR title. Use "Add feature: [Feature Name]", "Fix: [Bug Description]", or "Chore: [Description]".');
            }

            if (isFeature || isFix) {
              const mandatoryChecks = [
                '- [x] i have read the [contributing.md]',
                '- [x] i have performed at least one form of testing',
                '- [x] i have updated the documentation if necessary'
              ];
              const missingChecks = mandatoryChecks.filter(check => !prBody.includes(check));
              if (missingChecks.length > 0) {
                throw new Error('Mandatory checkboxes are missing or unchecked. Please ensure all mandatory checks are completed.');
              }
            }
